schema_version = "1.0.0"

id = "simplecleanuptools"
version = "1.3.0"
name = "Lichi's Random Tools"
tagline = "Some tools that ive found useful while modding BeamNG"
maintainer = "Lichi"
type = "add-on"
website = "https://github.com/lordlichi2006/"
tags = ["Tools"]

blender_version_min = "4.5.0"

license = [
  "MIT",
] 

copyright = [
   "2025 Lichi",
]
[permissions]
